### ISSUE TITLE
How do I pull the LFS files?

### ISSUE THREAD

**Issue by ngocnv371** [Senspark/cocos2d-x-3.15#1]
Hi, Good job doing this thing. I had been trying to get it to build to no avail for a long time.

When I run `git lfs pull` it ask for some password to a strange server. How do I download it?

**Comment by enrevol** [comment]
username: admin
password: admin

2017-09-23 21:35 GMT+07:00 Ngoc Ngo <notifications@github.com>:

**Comment by enrevol** [comment]
We use our server for faster git pull.
