### ISSUE TITLE
Prebuilt libs

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [Senspark/cocos2d-x-3.15#2]
Hello,

nice project. You removed really that things I wanted to removed by my self :)  
I wanted to ask how do you built prebuilt libs? Using latest tools? NDK? Are you already using c++_static ? 

Also check this https://github.com/KAMIKAZEUA/SpriteBuilderX  
But it's still using different repo..

**Comment by enrevol** [comment]
I have updated README, have a look at it.
Currently prebuilt libs are built with c++_static.
SpriteBuilderX is a nice project but we are already using our own CocosBuilder.

**Comment by Anywhere-Music-Player** [comment]
@enrevol The reason I'm asking about this is because of with official cocos2d-x repo I'm using:

`cocos gen-libs -p android --ap android-19 --app-abi x86:armeabi-v7a `

to generate libs for android. And when I changed to use c++_static I got problems with building some errors, build failed. So I wonder how these libs are built and with which NDK? tools version etc. ?

**Comment by enrevol** [comment]
Our settings (master branch):
- NDK r16
- NDK_TOOLCHAIN_VERSION=clang
- APP_STL=c++_static
- APP_PLATFORM=android-14
- Android SDK Tools 26.1.1

For r10e tag:
- Android NDK r10e
- Same toolchain and app_stl
- APP_PLATFORM=android-9
- Android SDK Tools 26.0.2
